"""Post an AO directive (CMD-AO2 S2): validate the directive/2 head with ga,
post it on the session's channel with a '[AO → X]' body head, and print the
comment URL plus the notify/1 line to send to the session.

usage: python3 ops/issue.py <spec.json> <body.md> <issue_number>
spec.json is the directive/2 head (schema, id, rev, to, goal, why, refs, scope, done_when, ...).
"""
import json
import subprocess
import sys
import tempfile

import ga.forms as forms

AO_SESSION = "session_01JWUCzhkqtsYpyJ6PyRq9cA"
REPO = "cogito5170/baseline"


def main():
    spec_p, body_p, issue = sys.argv[1], sys.argv[2], sys.argv[3]
    head = json.load(open(spec_p))
    assert head.get("schema") == "directive/2", "AO issues directive/2 only"
    probs = forms.validate(head)
    hard = forms.hard(probs)
    if hard:
        sys.exit(f"ga check failed: {hard}")
    body = open(body_p).read().strip()
    assert body.startswith(f"[AO → {head['to']}]"), "body must start with '[AO → <session>]'"
    text = ("```ga\n" + json.dumps(head, ensure_ascii=False) + "\n```\n" + body
            + f"\n\n**Notify back:** after your report on this issue, send `notify/1` to AO (`{AO_SESSION}`), not to baseline."
            + "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n")
    forms.parse_post(text)  # the posted form must parse too
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
        f.write(text)
    url = subprocess.run(["gh", "api", f"repos/{REPO}/issues/{issue}/comments", "-F", f"body=@{f.name}",
                          "--jq", ".html_url"], check=True, capture_output=True, text=True).stdout.strip()
    note = {"schema": "notify/1", "to": head["to"], "kind": "directive", "ref": url, "id": head["id"]}
    assert not forms.hard(forms.validate(note))
    print(url)
    print(json.dumps(note, ensure_ascii=False))


if __name__ == "__main__":
    main()
